application: juganville2
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: andromede.application
- url: /favicon\.ico
  static_files: static/img/favicon.png
  upload: static/img/favicon\.png
